### ISSUE TITLE
valgrind test 32 byte memory lose

### ISSUE THREAD

**Issue by am2222** [ashish157/QtKnobs#6]
Hi,
When I add this library into my application it causes 32 byte memory lost. Is there any way to fix it?
thanks

**Comment by ashish157** [comment]
Hi Majid,

Can you please look where the memory lose happens? i.e whether it is in Qt
library or QtKnobs or any other dependent library.

Thanks,
Ashish

**Comment by am2222** [comment]
@I will check it now, but when I remove QtKnobs from my application memory loss disappears
